# Generated by Django 5.1.4 on 2025-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
