# Generated by Django 5.1.4 on 2025-02-08 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0002_remove_kyc_verification_status_kyc_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('property_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stamp_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_deed', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
