# Generated by Django 5.1.4 on 2025-02-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0003_alter_kyc_phone_number_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpaschim', 'Sudurpaschim')], max_length=200),
        ),
    ]
