# Generated by Django 5.1.4 on 2025-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0004_alter_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
