# Generated by Django 5.1.4 on 2025-02-08 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0006_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
