# Generated by Django 5.1.4 on 2025-02-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0007_property_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='paid_amount',
        ),
    ]
