# Generated by Django 5.1.4 on 2025-02-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0009_remove_property_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
