# Generated by Django 5.1.4 on 2025-02-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0010_property_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
