# Generated by Django 5.1.4 on 2025-02-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertymanagement', '0011_property_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
